import * as fs from 'fs';
import * as path from 'path';

type RuleKind = 'effect' | 'trigger' | 'modifier' | 'scope' | 'localisation_command';

interface GeneratedRule {
    name: string;
    kind: RuleKind;
    scopes: string[];
    targetScopes: string[];
    parameters: Array<{ name: string; type: string }>;
    description: string;
    source: string;
    sourceLine: number;
    confidence: 'high' | 'medium' | 'low';
    needsManualReview: boolean;
}

interface RulesGenerated {
    effects: GeneratedRule[];
    triggers: GeneratedRule[];
    modifiers: GeneratedRule[];
    scopes: GeneratedRule[];
    localisationCommands: GeneratedRule[];
}

interface ReportEntry {
    kind: RuleKind;
    name: string;
    action: 'added' | 'skipped_existing' | 'conflict' | 'manual_review';
    targetFile?: string;
    reason?: string;
}

interface UpdateReport {
    checkedAt: string;
    checkOnly: boolean;
    generatedJson: string;
    existingRulesDir: string;
    summary: Record<string, number>;
    entries: ReportEntry[];
}

const KIND_FILES: Record<Exclude<RuleKind, 'localisation_command'>, string> = {
    effect: 'effects.generated.cwt',
    trigger: 'triggers.generated.cwt',
    modifier: 'modifiers.generated.cwt',
    scope: 'scopes.generated.cwt',
};

function walkCwtFiles(dir: string): string[] {
    if (!fs.existsSync(dir)) return [];
    const results: string[] = [];
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        const fullPath = path.join(dir, entry.name);
        if (entry.isDirectory()) results.push(...walkCwtFiles(fullPath));
        else if (entry.name.endsWith('.cwt')) results.push(fullPath);
    }
    return results;
}

function scanExistingRules(dir: string): Map<string, string[]> {
    const existing = new Map<string, string[]>();
    const add = (kind: RuleKind, name: string, file: string) => {
        const key = `${kind}:${name.toLowerCase()}`;
        const list = existing.get(key) ?? [];
        list.push(file);
        existing.set(key, list);
    };
    for (const file of walkCwtFiles(dir)) {
        const content = fs.readFileSync(file, 'utf-8');
        for (const match of content.matchAll(/alias\[(effect|trigger|modifier):([A-Za-z_][A-Za-z0-9_.-]*)\]/g)) {
            add(match[1] as RuleKind, match[2]!, file);
        }
        if (file.toLowerCase().includes('modifier')) {
            for (const match of content.matchAll(/^([A-Za-z_][A-Za-z0-9_.-]*)\s*=\s*\{/gm)) {
                add('modifier', match[1]!, file);
            }
        }
    }
    return existing;
}

function loadRules(filePath: string): RulesGenerated {
    return JSON.parse(fs.readFileSync(filePath, 'utf-8')) as RulesGenerated;
}

function allRules(rules: RulesGenerated): GeneratedRule[] {
    return [
        ...rules.effects,
        ...rules.triggers,
        ...rules.modifiers,
        ...rules.scopes,
        ...rules.localisationCommands,
    ];
}

function renderRule(rule: GeneratedRule): string {
    const review = rule.needsManualReview ? '\n## needs_manual_review = yes' : '';
    const scopes = rule.scopes.length ? `\n## supported_scopes = ${rule.scopes.join(' ')}` : '';
    switch (rule.kind) {
        case 'effect':
        case 'trigger':
            return `### ${rule.description || `Generated ${rule.kind}`}${scopes}${review}\nalias[${rule.kind}:${rule.name}] = {\n\t# TODO: verify generated parameters\n}`;
        case 'modifier':
            return `### ${rule.description || 'Generated modifier'}${review}\nalias[modifier:${rule.name}] = float`;
        case 'scope': {
            const push = rule.targetScopes[0] ? `## push_scope = ${rule.targetScopes[0]}\n` : '';
            return `${push}### ${rule.description || 'Generated scope change'}${scopes}${review}\nalias[trigger:${rule.name}] = { alias_name[trigger] = alias_match_left[trigger] }\nalias[effect:${rule.name}] = { alias_name[effect] = alias_match_left[effect] }`;
        }
        case 'localisation_command':
            return `## ${rule.description}\n# ${rule.scopes.join('.')}.${rule.name}`;
    }
}

function ensureHeader(filePath: string, kind: RuleKind) {
    if (fs.existsSync(filePath)) return;
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, `# <auto-generated:${kind}s>\n# Generated by tools/rules-sync/update-rules.ts. Review before merging into stable CWT.\n\n`, 'utf-8');
}

function appendRule(filePath: string, kind: RuleKind, rule: GeneratedRule) {
    ensureHeader(filePath, kind);
    fs.appendFileSync(filePath, `${renderRule(rule)}\n\n`, 'utf-8');
}

function createReport(generatedJson: string, existingRulesDir: string, checkOnly: boolean): UpdateReport {
    return {
        checkedAt: new Date().toISOString(),
        checkOnly,
        generatedJson: path.resolve(generatedJson),
        existingRulesDir: path.resolve(existingRulesDir),
        summary: { added: 0, skipped_existing: 0, conflict: 0, manual_review: 0 },
        entries: [],
    };
}

function record(report: UpdateReport, entry: ReportEntry) {
    report.entries.push(entry);
    report.summary[entry.action] = (report.summary[entry.action] ?? 0) + 1;
}

function run(generatedJson: string, existingRulesDir: string, outDir: string, checkOnly: boolean): UpdateReport {
    const rules = loadRules(generatedJson);
    const existing = scanExistingRules(existingRulesDir);
    const report = createReport(generatedJson, existingRulesDir, checkOnly);
    const generatedDir = path.join(outDir, 'generated');

    for (const rule of allRules(rules)) {
        if (rule.kind === 'localisation_command') {
            record(report, { kind: rule.kind, name: rule.name, action: 'manual_review', reason: 'Localisation command loader integration is manual for now.' });
            continue;
        }

        const existingFiles = existing.get(`${rule.kind}:${rule.name.toLowerCase()}`) ?? [];
        if (existingFiles.length > 0) {
            const reason = existingFiles.some(file => !file.includes(`${path.sep}generated${path.sep}`))
                ? 'Manual CWT rule already exists; kept manual rule.'
                : 'Generated rule already exists.';
            record(report, { kind: rule.kind, name: rule.name, action: existingFiles.some(file => !file.includes(`${path.sep}generated${path.sep}`)) ? 'conflict' : 'skipped_existing', reason });
            continue;
        }
        if (rule.needsManualReview || rule.confidence === 'low') {
            record(report, { kind: rule.kind, name: rule.name, action: 'manual_review', reason: `confidence=${rule.confidence}` });
            continue;
        }
        const targetFile = path.join(generatedDir, KIND_FILES[rule.kind]);
        record(report, { kind: rule.kind, name: rule.name, action: 'added', targetFile });
        if (!checkOnly) appendRule(targetFile, rule.kind, rule);
    }

    return report;
}

function parseArgs(argv: string[]) {
    const generatedJson = argv[0];
    const existingRulesDir = argv[1];
    const getArg = (name: string, fallback = '') => {
        const idx = argv.indexOf(name);
        return idx >= 0 && argv[idx + 1] ? argv[idx + 1]! : fallback;
    };
    return {
        generatedJson,
        existingRulesDir,
        outDir: getArg('--output', existingRulesDir ? path.join(existingRulesDir, 'generated-sync') : 'generated-sync'),
        checkOnly: argv.includes('--check'),
    };
}

function main() {
    const args = parseArgs(process.argv.slice(2));
    if (!args.generatedJson || !args.existingRulesDir) {
        console.error('Usage: npx ts-node tools/rules-sync/update-rules.ts <rules.generated.json> <existingRulesDir> [--output <outDir>] [--check]');
        process.exit(1);
    }
    fs.mkdirSync(args.outDir, { recursive: true });
    const report = run(args.generatedJson, args.existingRulesDir, args.outDir, args.checkOnly);
    const reportPath = path.join(args.outDir, args.checkOnly ? 'rules-sync-check-report.json' : 'rules-sync-update-report.json');
    fs.writeFileSync(reportPath, JSON.stringify(report, null, 2) + '\n', 'utf-8');
    console.log(`Report: ${reportPath}`);
    console.log(JSON.stringify(report.summary));
    if (args.checkOnly && (report.summary.added ?? 0) > 0) process.exitCode = 2;
}

main();
