/**
 * CWTools AI 模块 — 内置模型及服务商默认配置
 */

import type { AIProviderConfig } from '../../types';

export const BUILTIN_PROVIDERS: Record<string, AIProviderConfig> = {
    openai: {
        id: 'openai',
        registerUrl: 'https://platform.openai.com/api-keys',
        name: 'OpenAI',
        endpoint: 'https://api.openai.com/v1',
        defaultModel: 'gpt-5.5',
        models: ['gpt-5.5', 'gpt-5.5-pro', 'gpt-5.5-instant', 'gpt-5.4', 'gpt-5.4-mini', 'gpt-5.4-nano', 'gpt-5.3-instant', 'gpt-5-mini', 'gpt-5-nano'],
        supportsToolUse: true,
        requiresApiKey: true,
        supportsStreaming: true,
        maxContextTokens: 400000,
        isOpenAICompatible: true,
        toolCallStyle: 'openai',
        supportsFIM: false,
        supportsVision: true,
    },
    claude: {
        id: 'claude',
        registerUrl: 'https://console.anthropic.com/',
        name: 'Claude (Anthropic)',
        endpoint: 'https://api.anthropic.com/v1',
        defaultModel: 'claude-opus-4-7',
        models: [
            'claude-opus-4-7',
            'claude-opus-4-6',
            'claude-sonnet-4-6',
            'claude-haiku-4-5',
        ],
        supportsToolUse: true,
        requiresApiKey: true,
        supportsStreaming: true,
        maxContextTokens: 1000000,
        isOpenAICompatible: false,
        toolCallStyle: 'openai',
        supportsFIM: false,
        supportsVision: true,
    },
    deepseek: {
        id: 'deepseek',
        registerUrl: 'https://platform.deepseek.com/',
        name: 'DeepSeek',
        endpoint: 'https://api.deepseek.com/v1',
        defaultModel: 'deepseek-v4-pro',
        models: ['deepseek-v4-pro', 'deepseek-v4-flash'],
        supportsToolUse: true,
        requiresApiKey: true,
        supportsStreaming: true,
        maxContextTokens: 1048576,
        isOpenAICompatible: true,
        toolCallStyle: 'openai',
        supportsFIM: true,
        supportsVision: false,
    },
    minimax: {
        id: 'minimax',
        registerUrl: 'https://minimaxi.com/',
        name: 'MiniMax (按量计费)',
        endpoint: 'https://api.minimaxi.com/v1',
        defaultModel: 'MiniMax-M2.7',
        models: ['MiniMax-M2.7', 'MiniMax-M2.7-highspeed', 'MiniMax-M2.5', 'MiniMax-M2.5-highspeed', 'MiniMax-M2.1', 'MiniMax-M2'],
        supportsToolUse: true,
        requiresApiKey: true,
        supportsStreaming: true,
        maxContextTokens: 200000,
        isOpenAICompatible: true,
        toolCallStyle: 'openai',
        supportsFIM: false,
        supportsVision: false,
    },
    'minimax-token-plan': {
        id: 'minimax-token-plan',
        registerUrl: 'https://minimaxi.com/',
        name: 'MiniMax Token Plan',
        endpoint: 'https://api.minimaxi.com/anthropic/v1',
        defaultModel: 'MiniMax-M2.7',
        models: ['MiniMax-M2.7', 'MiniMax-M2.7-highspeed', 'MiniMax-M2.5', 'MiniMax-M2.5-highspeed', 'MiniMax-M2.1', 'MiniMax-M2'],
        supportsToolUse: true,
        requiresApiKey: true,
        supportsStreaming: true,
        maxContextTokens: 200000,
        isOpenAICompatible: false,
        toolCallStyle: 'openai',
        supportsFIM: false,
        supportsVision: false,
    },
    glm: {
        id: 'glm',
        registerUrl: 'https://bigmodel.cn/',
        name: 'GLM (智谱 Zhipu)',
        endpoint: 'https://open.bigmodel.cn/api/paas/v4',
        defaultModel: 'glm-5.1',
        models: [
            'glm-5.1',
            'glm-5',
            'glm-5-turbo',
            'glm-5v-turbo',
            'glm-4.1v-thinking',
            'glm-4.1v-thinking-flash',
            'glm-4.7',
            'glm-4.7-flash',
            'glm-z1-flash',
            'glm-4-flash',
        ],
        supportsToolUse: true,
        requiresApiKey: true,
        supportsStreaming: true,
        maxContextTokens: 200000,
        isOpenAICompatible: true,
        toolCallStyle: 'openai',
        supportsFIM: false,
        supportsVision: true,
    },
    qwen: {
        id: 'qwen',
        registerUrl: 'https://dashscope.console.aliyun.com/',
        name: 'Qwen (通义千问)',
        endpoint: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
        defaultModel: 'qwen3.6-plus',
        models: [
            'qwen3.6-max-preview',
            'qwen3.6-plus',
            'qwen3.5-plus',
            'qwen3.6-flash',
            'qwen3-235b-a22b',
            'qwen3-32b',
            'qwen-max',
            'qwen-turbo',
            'qwen-long',
        ],
        supportsToolUse: true,
        requiresApiKey: true,
        supportsStreaming: true,
        maxContextTokens: 1000000,
        isOpenAICompatible: true,
        toolCallStyle: 'openai',
        supportsFIM: false,
        supportsVision: false,
    },
    mimo: {
        id: 'mimo',
        registerUrl: 'https://api.xiaomimimo.com/',
        name: 'MiMo (小米)',
        endpoint: 'https://api.xiaomimimo.com/v1',
        defaultModel: 'mimo-v2.5-pro',
        models: ['mimo-v2.5-pro', 'mimo-v2.5', 'mimo-v2-pro', 'mimo-v2-omni', 'mimo-v2-flash'],
        supportsToolUse: true,
        requiresApiKey: true,
        supportsStreaming: true,
        maxContextTokens: 1000000,
        isOpenAICompatible: true,
        toolCallStyle: 'openai',
        supportsFIM: false,
        supportsVision: true,
    },
    'mimo-token-plan': {
        id: 'mimo-token-plan',
        name: 'MiMo Token Plan (小米)',
        endpoint: 'https://token-plan-cn.xiaomimimo.com/v1',
        defaultModel: 'mimo-v2.5-pro',
        models: ['mimo-v2.5-pro', 'mimo-v2.5', 'mimo-v2-pro', 'mimo-v2-omni', 'mimo-v2-flash'],
        supportsToolUse: true,
        requiresApiKey: true,
        supportsStreaming: true,
        maxContextTokens: 1000000,
        isOpenAICompatible: true,
        toolCallStyle: 'openai',
        supportsFIM: false,
        supportsVision: true,
    },
    google: {
        id: 'google',
        name: 'Google (Gemini)',
        endpoint: 'https://generativelanguage.googleapis.com/v1beta/openai',
        defaultModel: 'gemini-2.5-pro',
        models: [
            'gemini-3.1-pro-preview',
            'gemini-3-flash-preview',
            'gemini-3.1-flash-lite-preview',
            'gemini-2.5-pro',
            'gemini-2.5-flash',
            'gemini-2.5-flash-lite',
        ],
        supportsToolUse: true,
        requiresApiKey: true,
        supportsStreaming: true,
        maxContextTokens: 1048576,
        isOpenAICompatible: true,
        toolCallStyle: 'openai',
        supportsFIM: false,
        supportsVision: true,
    },
    ollama: {
        id: 'ollama',
        registerUrl: 'https://ollama.com/',
        name: 'Ollama (本地模型)',
        endpoint: 'http://localhost:11434/v1',
        defaultModel: '',
        models: [],
        supportsToolUse: true,
        requiresApiKey: false,
        supportsStreaming: true,
        maxContextTokens: 32768,
        isOpenAICompatible: true,
        toolCallStyle: 'openai',
        supportsFIM: true,
        supportsVision: true,
    },
    custom: {
        id: 'custom',
        name: '自定义渠道 (OpenAI 兼容)',
        endpoint: '',
        defaultModel: '',
        models: [],
        supportsToolUse: true,
        requiresApiKey: true,
        supportsStreaming: true,
        maxContextTokens: 128000,
        isOpenAICompatible: true,
        toolCallStyle: 'openai',
        supportsFIM: true,
        supportsVision: true,
    },
    siliconflow: {
        id: 'siliconflow',
        registerUrl: 'https://cloud.siliconflow.cn/',
        name: 'SiliconFlow (硅基流动)',
        endpoint: 'https://api.siliconflow.cn/v1',
        defaultModel: 'deepseek-ai/DeepSeek-V4-Pro',
        models: [
            'deepseek-ai/DeepSeek-V4-Pro',
            'deepseek-ai/DeepSeek-V4-Flash',
            'Pro/zai-org/GLM-5.1',
            'Pro/moonshotai/Kimi-K2.6'
        ],
        supportsToolUse: true,
        requiresApiKey: true,
        supportsStreaming: true,
        maxContextTokens: 1048576,
        isOpenAICompatible: true,
        toolCallStyle: 'openai',
        supportsFIM: true,
        supportsVision: false,
    },
    openrouter: {
        id: 'openrouter',
        registerUrl: 'https://openrouter.ai/keys',
        name: 'OpenRouter',
        endpoint: 'https://openrouter.ai/api/v1',
        defaultModel: 'deepseek/deepseek-v4-pro',
        models: [
            'deepseek/deepseek-v4-pro',
            'anthropic/claude-4.7-opus',
            'anthropic/claude-4.6-sonnet',
            'google/gemini-3.1-pro',
            'google/gemini-3.5-flash',
            'openai/gpt-5.5',
            'openai/gpt-5-mini'
        ],
        supportsToolUse: true,
        requiresApiKey: true,
        supportsStreaming: true,
        maxContextTokens: 200000,
        isOpenAICompatible: true,
        toolCallStyle: 'openai',
        supportsFIM: true,
        supportsVision: true,
    },
    github: {
        id: 'github',
        registerUrl: 'https://github.com/marketplace/models',
        name: 'GitHub Models',
        endpoint: 'https://models.inference.ai.azure.com',
        defaultModel: 'DeepSeek-V4-Pro',
        models: [
            'DeepSeek-V4-Pro',
            'gpt-5.5',
            'gpt-5-mini',
            'claude-4.6-sonnet'
        ],
        supportsToolUse: true,
        requiresApiKey: true,
        supportsStreaming: true,
        maxContextTokens: 200000,
        isOpenAICompatible: true,
        toolCallStyle: 'openai',
        supportsFIM: false,
        supportsVision: true,
    },
    together: {
        id: 'together',
        registerUrl: 'https://api.together.xyz/',
        name: 'Together AI',
        endpoint: 'https://api.together.xyz/v1',
        defaultModel: 'deepseek-ai/DeepSeek-V4-Pro',
        models: [
            'deepseek-ai/DeepSeek-V4-Pro'
        ],
        supportsToolUse: true,
        requiresApiKey: true,
        supportsStreaming: true,
        maxContextTokens: 1048576,
        isOpenAICompatible: true,
        toolCallStyle: 'openai',
        supportsFIM: true,
        supportsVision: false,
    },
    deepinfra: {
        id: 'deepinfra',
        registerUrl: 'https://deepinfra.com/dash/api_keys',
        name: 'DeepInfra',
        endpoint: 'https://api.deepinfra.com/v1/openai',
        defaultModel: 'deepseek-ai/DeepSeek-V4-Pro',
        models: [
            'deepseek-ai/DeepSeek-V4-Pro'
        ],
        supportsToolUse: true,
        requiresApiKey: true,
        supportsStreaming: true,
        maxContextTokens: 1048576,
        isOpenAICompatible: true,
        toolCallStyle: 'openai',
        supportsFIM: true,
        supportsVision: false,
    },
    opencode: {
        id: 'opencode',
        name: 'OpenCode Zen',
        endpoint: 'https://opencode.ai/zen/v1',
        defaultModel: 'big-pickle (免费)',
        models: [
            'big-pickle (免费)',
            'minimax-m2.5-free (免费)',
            'deepseek-v4-flash-free (免费)',
            'nemotron-3-super-free (免费)',
            'ring-2.6-1t-free (免费)',
            'claude-haiku-4-5',
            'claude-opus-4-1',
            'claude-opus-4-5',
            'claude-opus-4-6',
            'claude-opus-4-7',
            'claude-sonnet-4',
            'claude-sonnet-4-5',
            'claude-sonnet-4-6',
            'gemini-3-flash',
            'gemini-3.1-pro',
            'glm-5',
            'glm-5.1',
            'gpt-5',
            'gpt-5-codex',
            'gpt-5-nano',
            'gpt-5.1',
            'gpt-5.1-codex',
            'gpt-5.1-codex-max',
            'gpt-5.1-codex-mini',
            'gpt-5.2',
            'gpt-5.2-codex',
            'gpt-5.3-codex',
            'gpt-5.3-codex-spark',
            'gpt-5.4',
            'gpt-5.4-mini',
            'gpt-5.4-nano',
            'gpt-5.4-pro',
            'gpt-5.5',
            'gpt-5.5-pro',
            'kimi-k2.5',
            'kimi-k2.6',
            'minimax-m2.5',
            'minimax-m2.7',
            'qwen3.5-plus',
            'qwen3.6-plus',
            'trinity-large-preview'
        ],
        supportsToolUse: true,
        requiresApiKey: true,
        supportsStreaming: true,
        maxContextTokens: 200000,
        isOpenAICompatible: true,
        toolCallStyle: 'openai',
        supportsFIM: false,
        supportsVision: true,
    },
    kimi: {
        id: 'kimi',
        registerUrl: 'https://platform.moonshot.cn/',
        name: 'Kimi (月之暗面)',
        endpoint: 'https://api.moonshot.ai/v1',
        defaultModel: 'kimi-k2.6',
        models: [
            'kimi-k2.6',
            'kimi-k2.5'
        ],
        supportsToolUse: true,
        requiresApiKey: true,
        supportsStreaming: true,
        maxContextTokens: 262144,
        isOpenAICompatible: true,
        toolCallStyle: 'openai',
        supportsFIM: false,
        supportsVision: true,
    }
};
