#!/usr/bin/env node
'use strict';
const fs = require('fs');
const path = require('path');
const JSZip = require('jszip');
const { platforms, sha256, validateNativeBytes } = require('./release-platforms.cjs');
const REQUIRED = Object.fromEntries(platforms.map(platform => ['extension/bin/server/' + platform.rid + '/' + platform.stagedBinary, buffer => validateNativeBytes(platform, buffer)]));
const FORBIDDEN = /(?:^|\/)(?:server-rust|src\/Main|src\/LSP|CWToolsTests|oracle|differential|sidecar)(?:\/|$)|\.(?:dll|deps\.json|runtimeconfig\.json|fs|fsx|fsproj|cs|csproj|sln|slnx)$/i;
async function validateVsix(vsixPath, options = {}) {
  const archive = await JSZip.loadAsync(fs.readFileSync(vsixPath)); const names = Object.keys(archive.files).filter(name => !archive.files[name].dir); const errors = []; const hashes = new Set();
  for (const platform of platforms) { const name = 'extension/bin/server/' + platform.rid + '/' + platform.stagedBinary; const entry = archive.file(name); if (!entry) { errors.push('missing ' + name); continue; } const buffer = await entry.async('nodebuffer'); if (!validateNativeBytes(platform, buffer)) errors.push('invalid native executable signature for ' + name); hashes.add(sha256(buffer)); }
  if (hashes.size !== platforms.length) errors.push('native server artifacts are not three distinct binaries');
  for (const name of names) if (FORBIDDEN.test(name)) errors.push('forbidden migration/.NET artifact: ' + name);
  const expectedServers = new Set(Object.keys(REQUIRED)); for (const name of names.filter(name => name.startsWith('extension/bin/server/'))) if (!expectedServers.has(name)) errors.push('unexpected server artifact: ' + name);
  if (names.some(name => name.startsWith('extension/bin/mcp/'))) errors.push('MCP must not be bundled in the universal VSIX');
  for (const required of ['extension/package.json', 'extension/readme.md', 'extension/rules/stellaris-rules.zip', 'extension/rules/stellaris-rules.version.json', 'extension/release-provenance.json']) if (!archive.file(required)) errors.push('missing ' + required);
  const packageEntry = archive.file('extension/package.json'); if (packageEntry) { const packaged = JSON.parse(await packageEntry.async('string')); const local = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'release', 'package.json'), 'utf8')); if (packaged.version !== local.version) errors.push('VSIX version does not match release/package.json'); const expectedName = 'foreverskywalker-stellaris-cwtools-' + packaged.version + '.vsix'; if (path.basename(vsixPath) !== expectedName) errors.push('VSIX filename does not match packaged version: expected ' + expectedName); }
  const provenanceEntry = archive.file('extension/release-provenance.json'); if (provenanceEntry) { const provenance = JSON.parse(await provenanceEntry.async('string')); if (provenance.schemaVersion !== 1 || !Array.isArray(provenance.platforms) || provenance.platforms.length !== platforms.length) errors.push('invalid release provenance schema'); if (options.sourceSha && provenance.sourceSha !== options.sourceSha.toLowerCase()) errors.push('release provenance source SHA mismatch'); for (const platform of platforms) { const item = provenance.platforms && provenance.platforms.find(value => value.rid === platform.rid); const entry = archive.file('extension/bin/server/' + platform.rid + '/' + platform.stagedBinary); if (!item || !entry) continue; const bytes = await entry.async('nodebuffer'); if (item.target !== platform.target || item.stagedBinary !== platform.stagedBinary || item.size !== bytes.length || item.sha256 !== sha256(bytes)) errors.push('release provenance mismatch for ' + platform.rid); } }
  return { errors, names, serverFiles: names.filter(name => name.startsWith('extension/bin/server/')) };
}
async function main(argv) { const i = argv.indexOf('--vsix'); const vsixPath = i >= 0 ? argv[i + 1] : undefined; const s = argv.indexOf('--source-sha'); const sourceSha = s >= 0 ? argv[s + 1] : undefined; if (!vsixPath || vsixPath.startsWith('--')) throw new Error('--vsix requires a file'); const absolute = path.resolve(vsixPath); if (!fs.existsSync(absolute)) throw new Error('VSIX not found: ' + absolute); const result = await validateVsix(absolute, { sourceSha }); if (result.errors.length) { for (const error of result.errors) console.error('FAIL: ' + error); return 1; } console.log('Universal VSIX gate passed: exact versioned artifact, provenance, three distinct native Rust servers, and no migration/.NET runtime artifacts.'); return 0; }
if (require.main === module) main(process.argv.slice(2)).then(code => { process.exitCode = code; }).catch(error => { console.error(error.message || error); process.exitCode = 1; });
module.exports = { REQUIRED, validateVsix };
